### ISSUE TITLE
Add workflow to auto add new issues to astriaorg master project

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/dev-cluster#20]
See: https://github.com/actions/add-to-project

Attempting to follow these instructions (https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/adding-items-automatically) and duplicating the existing workflow gives a message of "maximum number of auto-add workflows reached" but we may be able to manually add an action. 

Example from above link:
```
name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, needs-triage
          label-operator: OR
```

Note: we want to leave the `labeled` input empty which will add all issues

![Screenshot 2023-06-14 at 8 13 30 PM](https://github.com/astriaorg/dev-cluster/assets/5825193/d3595cd4-a639-4ae1-bdbe-17f02d775ccb)
